### ISSUE TITLE
ERROR: WFLYCTL0031: No operation named 'add' exists at address

### ISSUE THREAD

**Issue by sixturtle** [spaulg/wildfly#1]
I tried to merge it to 10.0.0.Final but tests are failing with following error. E.g. OperationSequencesTestCase#testCacheContainerAddRemoveAddSequence()

```
Jun 03, 2016 4:05:57 PM org.jboss.as.controller.ModelControllerImpl logNoHandler
ERROR: WFLYCTL0031: No operation named 'add' exists at address [
    ("subsystem" => "infinispan"),
    ("cache-container" => "maximal"),
    ("local-cache" => "redis"),
    ("store" => "redis")
]
```

**Comment by spaulg** [comment]
Yes its incomplete. It is a fork of the main repository to add Redis support using the Redis infinispan store driver that I wrote, however it never got finished and finishing it isn't a priority.
